### ISSUE TITLE
Crash on using /spawn cmd

### ISSUE THREAD

**Issue by NillerMedDild** [Elrol/Server-Utilities#12]
I used the `/spawn` command in a single player world without cheats enabled, crashed.
https://gist.github.com/NillerMedDild/4a841e80a8baface660f55e87c9ab14e

**Comment by Elrol** [comment]
I have not been able to replicate this issue. However when trying this out I noticed that players can use any command because one of the checks for permission (the one checking if commands are enabled for all) returns true, even when no cheats are used. So theres that. If you can give me a log then I might be able to see more of what happened.

**Comment by NillerMedDild** [comment]
Damn, that's one hell of a bug. I'm afraid I don't have any logs, I thought the crash report would suffice.

**Comment by Elrol** [comment]
If you are able to do it again let me know, I will keep trying. The crash basically told me that the class that i use for all the commands is not there, but its hard coded into each of the command classes. So from what I can see, there should not be a way for that class to not exist, but that doesnt mean that I will give up, you got a crash, it says its my mod, I will work to fix that.

**Comment by NillerMedDild** [comment]
I can't reproduce this issue anymore \o/
