### ISSUE TITLE
Warp name not displaying

### ISSUE THREAD

**Issue by NillerMedDild** [Elrol/Server-Utilities#8]
Hello!

I've noticed that the name of warps is not displayed correctly when using `/warm <name>`
It displays `Welcome to .`
![billede](https://user-images.githubusercontent.com/21295394/68155472-0f3f9a00-ff4a-11e9-8451-273dd12cb20b.png)

Elrols Utilities-1.14.4-0.8.2

**Comment by Elrol** [comment]
Very odd, it shpuld be a simple fix. I will take care of that in the next hour or so

**Comment by Elrol** [comment]
It should be fixed in the most recent build. Somehow i forgot a simple little letter. But that file has a decent amount of localizations. 

https://www.curseforge.com/minecraft/mc-mods/elrols-server-utilities/files/2822160

Sorry it took a bit to fix, saw the issue was opened an hour ago and I was sleeping, but fixed it first thing.

**Comment by NillerMedDild** [comment]
Thanks :D happens!

No worries at all, I thought you were pretty quick to fix it tbh. Programmers need sleep too! :P

**Comment by Elrol** [comment]
haha, Glad to have fixed it, if you have any other issues or suggestions let me know :D
